import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";
import { HiMagnifyingGlass } from "react-icons/hi2";
import { BiMicrophone } from "react-icons/bi";
import { TbGridDots } from "react-icons/tb";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;
    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-full h-14 justify-between">
        <div className="flex items-center">
          <a
            className="p-1 m1 link"
            href="https://about.google/?fg=1&utm_source=google-AU&utm_medium=referral&utm_campaign=hp-header"
          >
            About
          </a>
          <a
            className="p-1 m2 link"
            href="https://store.google.com/AU/?utm_source=hp_header&utm_medium=google_ooo&utm_campaign=GS100042&hl=en-AU&pli=1"
          >
            Store
          </a>
        </div>

        <div className="flex items-center  justify-end">
          <div className="">
            <a
              className="m3 link"
              href="https://mail.google.com/mail/u/0/?ogbl"
            >
              Gmail
            </a>
            <a className="m3 link" href="">
              Images
            </a>
          </div>

          <div className="flex space-x-4 mr-6 ml-4">
            <TbGridDots className="h-10 w-10 p-2 rounded-full text-[#676c70] hover:bg-gray-200 cursor-pointer" />
            <button
              type="button"
              className="bg-[#1a73e8] text-white button smw hover:shadow-md"
            >
              Sign in
            </button>
          </div>
        </div>
      </header>

      <form className="flex flex-col items-center mt-56 flex-grow w-4/5">
        <Image
          src={
            "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          }
          height={92}
          width={272}
        />

        <div className="flex w-full mt-7 hover:shadow-lg focus-within:shadow-md max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <HiMagnifyingGlass className="h-5 mr-3 text-[#202124]" />
          <input
            ref={searchInputRef}
            type="text"
            className=" flex-grow focus: outline-none"
          />
          <BiMicrophone className="h-5 cursor-pointer" />
        </div>

        <div className="flex space-x-3 mt-8">
          <button className="btn" onClick={search}>
            Google Search
          </button>
          <button className="btn">I'm Feeling Lucky</button>
        </div>
      </form>

      <Footer />
    </div>
  );
}
